// Auto-generated by publish.ps1
const portfolioProjects = [
    {
        title: "Birthday Loading",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/BIRTHDAY LOADING.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Brie Beauty Ad",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Brie Beauty ad.jpg",
        width: 1920,
        height: 2400,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Insight Media Ad 2",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Insight Media ad 2.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Sawasawa Happy New Year",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Sawasawa Happy New Year.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Sawasawa Merry Christmas",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Sawasawa Merry Christmas.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Shukez Photography Chilembwe Day",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Shukez Photography Chilembwe Day.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Shukez Photography Merry Christmas",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Shukez Photography Merry Christmas.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Thandie Save The Date",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/Thandie Save the Date.jpg",
        width: 1920,
        height: 2496,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Valentine Waimvera Fungo",
        category: "Graphic Design",
        folder: "showcase",
        image: "works/showcase/VALENTINE WAIMVERA FUNGO.jpg",
        width: 1920,
        height: 2348,
        isRecent: false,
        isFeatured: true,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Harriet Closet Logo",
        category: "Logo Design & Branding",
        folder: "branding",
        image: "works/branding/Harriet Closet Logo copy.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Logo Design & Branding"
    },
    {
        title: "Montie Logo",
        category: "Logo Design & Branding",
        folder: "branding",
        image: "works/branding/MONTIE LOGO.png",
        width: 1920,
        height: 1571,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Logo Design & Branding"
    },
    {
        title: "Harriet Closet",
        category: "Marketing Materials",
        folder: "marketing",
        image: "works/marketing/HARRIET CLOSET.jpg",
        width: 1920,
        height: 2400,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Marketing Materials"
    },
    {
        title: "Romuths Ad",
        category: "Marketing Materials",
        folder: "marketing",
        image: "works/marketing/Romuths Ad.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Marketing Materials"
    },
    {
        title: "Andrina Elegant Nails",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/ANDRINA ELEGANT NAILS.jpg",
        width: 1920,
        height: 2400,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Another",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/Another.jpg",
        width: 1920,
        height: 1920,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Chididi Sda Correction",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/CHIDIDI SDA CORRECTION.jpg",
        width: 1920,
        height: 1920,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Get Together",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/GET TOGETHER.jpg",
        width: 1920,
        height: 2328,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Insight Media Ad 1",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/Insight Media ad 1.jpg",
        width: 1920,
        height: 1920,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Mphungu Investments Ad",
        category: "Graphic Design",
        folder: "recent",
        image: "works/recent/Mphungu Investments ad.jpg",
        width: 1920,
        height: 2460,
        isRecent: true,
        isFeatured: false,
        featuredCategory: "Graphic Design"
    },
    {
        title: "Farm Stew Certificate Of Completion",
        category: "Print Design",
        folder: "print",
        image: "works/print/FARM STEW CERTIFICATE OF COMPLETION.jpg",
        width: 1920,
        height: 1357,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Print Design"
    },
    {
        title: "Jay Dada Ep",
        category: "Illustration",
        folder: "illustration",
        image: "works/illustration/JAY DADA EP.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Illustration"
    },
    {
        title: "Kitchen Party Invitation Card",
        category: "Illustration",
        folder: "illustration",
        image: "works/illustration/Kitchen Party Invitation Card.jpg",
        width: 1920,
        height: 1920,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Illustration"
    },
    {
        title: "Queen",
        category: "Illustration",
        folder: "illustration",
        image: "works/illustration/Queen.jpg",
        width: 1920,
        height: 2400,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Illustration"
    },
    {
        title: "Thandie Wedding Card",
        category: "Illustration",
        folder: "illustration",
        image: "works/illustration/Thandie Wedding Card.jpg",
        width: 1920,
        height: 1536,
        isRecent: false,
        isFeatured: false,
        featuredCategory: "Illustration"
    }
];

